### ISSUE TITLE
Update to ETS5?

### ISSUE THREAD

**Issue by pfisterer** [tuxedo0801/ETS4Reader#1]
Hi @tuxedo0801, 

I'm currently experimenting with exporting ETS5 files to Openhab and found your project. Do you have any plans to update this to ETS5?

I could also contribute but I currently do have issues understanding, how `ComObjectInstanceRef`s work in the new format.

For instance, they are as follows: 

```XML
<ComObjectInstanceRefs>
                  <ComObjectInstanceRef RefId="O-0_R-1" Links="GA-7 GA-226" />
                  <ComObjectInstanceRef RefId="O-12_R-26" Links="GA-211" />
</ComObjectInstanceRefs>
```

I'm not quite sure how to resolve the RefId.

Best,
Dennis

**Comment by tuxedo0801** [comment]
pls refer to the updated project: https://gitlab.com/alexanderchristian/KnxProjParser
